services:
  dev:
    image: queaming/daffy-dev
    container_name: daffy-dev-hot
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: npm run dev:hot
    depends_on:
      - postgres-db
  postgres-db:
    image: queaming/mm-postgres
    container_name: mm-database
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=mmadmin
      - POSTGRES_DB=mmdb
    volumes:
      - dev-db-volume:/var/lib/postgresql/database
volumes:
  node_modules:
  dev-db-volume:
