# Stage 1: Build the backend
FROM node:20.18.0

RUN npm install --global webpack

# Set working directory
WORKDIR /app

# Copy package files first (for better caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose port 3000
EXPOSE 3000
